name: change_application_name_project

packages:
  - apps/**
  - packages/**

scripts:
  get:
    run: |
      melos exec -c 1 -- \
        flutter pub get
    description: Get dependencies for all packages
  restart:
    run: |
      melos exec -c 1 -- \
        "flutter clean && flutter pub get"
    description: Restart dependencies for all packages
  upgrade:
    run: |
      melos exec -c 1 -- \
        flutter pub upgrade
    description: Upgrade dependencies in all packages
  outdated:
    run: |
      melos exec -c 1 -- \
        flutter pub outdated
    description: Check outdated dependencies

  build_runner:
    run: |
      melos exec -c 1 -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build_runner in all packages

  gen:
    run: |
      melos exec -c 1 -- \
        "fluttergen"
    description: Generate all assets

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"

    dependencies:
      json_annotation: ^4.9.0

    dev_dependencies:
      flutter_lints: ^5.0.0
      build_runner: ^2.4.15
      freezed: ^3.0.6
      json_serializable: ^6.9.4
      flutter_gen_runner: ^5.10.0

