name: localization
description: Project localization.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  slang: ^4.6.0
  slang_flutter: ^4.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.6.0

flutter_gen:
  output: lib/generated/

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter

flutter:
  uses-material-design: true
  generate: true
