import 'package:design_system/lib.dart';

class BodyWrapLayout extends WrapLayout {
  const BodyWrapLayout({
    super.key,
    super.ratio,
    super.width = double.infinity,
    super.height,
    super.minWidth,
    super.maxWidth,
    super.minHeight,
    super.maxHeight,
    super.rotate,
    super.decoration,
    super.padding,
    super.margin,
    super.border,
    super.borderRadius,
    super.backgroundColor,
    super.backgroundGradient,
    super.backgroundImage,
    super.foregroundColor,
    super.foregroundGradient,
    super.foregroundImage,
    super.opacity,
    super.clipBehavior,
    super.innerShadow,
    super.dropShadow,
    super.backgroundBlur,
    super.transform,
    super.direction,
    super.alignment = WrapAlignment.center,
    super.spacing,
    super.runAlignment,
    super.runSpacing,
    super.crossAxisAlignment,
    super.textDirection,
    super.verticalDirection,
    super.gap,
    super.scrollable,
    required super.children,
  });
}
