name: change_application_name
description: "A change your project name."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  data:
    path: ../../packages/data
  design_system:
    path: ../../packages/design_system
  localization:
    path: ../../packages/localization
  utils:
    path: ../../packages/utils

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  country_code_picker: ^3.3.0

  #======= UI ========#
  #PLATFORM: All
  pinput: ^5.0.1
  feedback: ^3.1.0

  #======= DATA ========#
  #PLATFORM: All
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  envied: ^1.1.1

  #========== Utils ===========#
  flutter_multi_formatter: ^2.13.7
  talker_bloc_logger: ^4.7.1
  sms_autofill: ^2.4.1
  auto_route: ^10.0.1

dependency_overrides:
  # Resolve for wechat_assets_picker
  extended_image: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr:
    git:
      url: https://github.com/Nextzy/flutter_flavorizr
      ref: master

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_web_compilers: ^4.1.3
  json_serializable: ^6.9.4
  freezed: ^3.0.6
  drift_dev: ^2.26.0
  envied_generator: ^1.1.1
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

###################################################
# FLUTTER FLAVORIZR                               #
# Run command: flutter pub run flutter_flavorizr  #
###################################################
flavorizr: #See more: https://pub.dev/packages/flutter_flavorizr
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      buildSettings:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon-$(ASSET_PREFIX)" # Make AppIcon compatible with flutter_launcher_icons
    macos:
      buildSettings:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon-$(ASSET_PREFIX)" # Make AppIcon compatible with flutter_launcher_icons
  flavors:
    dev:
      app:
        name: "Template (Dev)"
      android:
        applicationId: "com.change_application_name.dev"
        generateDummyAssets: false
        firebase:
          config: "configs/firebase/dev/google-services.json"
      ios:
        bundleId: "com.change_application_name.dev"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenDev"
        firebase:
          config: "configs/firebase/dev/GoogleService-Info.plist"
      macos:
        bundleId: "com.change_application_name.dev"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenDev"
        firebase:
          config: "configs/firebase/dev/GoogleService-Info.plist"
    uat:
      app:
        name: "Template (UAT)"
      android:
        applicationId: "com.change_application_name.uat"
        generateDummyAssets: false
        firebase:
          config: "configs/firebase/uat/google-services.json"
      ios:
        bundleId: "com.change_application_name.uat"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenUat"
        firebase:
          config: "configs/firebase/uat/GoogleService-Info.plist"
      macos:
        bundleId: "com.change_application_name.uat"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenUat"
        firebase:
          config: "configs/firebase/uat/GoogleService-Info.plist"
    prod:
      app:
        name: "Template"
      android:
        applicationId: "com.change_application_name"
        generateDummyAssets: false
        firebase:
          config: "configs/firebase/prod/google-services.json"
      ios:
        bundleId: "com.change_application_name"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenProd"
        firebase:
          config: "configs/firebase/prod/GoogleService-Info.plist"
      macos:
        bundleId: "com.change_application_name"
        generateDummyAssets: false
        buildSettings:
          LAUNCH_SCREEN_STORYBOARD: "LaunchScreenProd"
        firebase:
          config: "configs/firebase/prod/GoogleService-Info.plist"

  instructions:
    - assets:download
    - assets:extract
    - android:flavorizrGradle
    - android:buildGradle
    - ios:podfile
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - macos:podfile
    - macos:xcconfig
    - macos:configs
    - macos:buildTargets
    - macos:schema
    - macos:plist
    - google:firebase
    - huawei:agconnect
    - assets:clean